---
# tasks file for install puppet-agent on Linux

- name: Update apt cache on Debian Family os
  apt:
    update_cache: yes
  changed_when: false
  when: ansible_os_family == "Debian"

- name: Update emerge cache on Gentoo
  command: emerge-webrsync
  changed_when: false
  when: ansible_os_family == "Gentoo"

- name: Install puppet-agent from Puppetlabs repository on Linux
  package:
    name: puppet-agent
    state: present
  when: install_from == "puppetlabs_repository"

- name: Install puppet-agent from os repository on Linux
  package:
    name: "{{ puppet_agent_package }}"
    state: present
  when: install_from == "os_repository"

- name: Puppet-agent service on Linux
  service:
    name: "{{ puppet_agent_service }}"
    state: started
    enabled: yes
