---
# Install puppet-agent on osx

- name: Darwin | Check if puppet is installed
  stat:
    path: /opt/puppetlabs/bin/puppet
  register: puppet_package

- name: Darwin | Install and manage puppet-agent
  block:

    - name: Darwin | Temporary directory
      file:
        path: ./tmp
        state: directory

    - name: Darwin | Download puppet-agent package
      get_url:
        url: https://downloads.puppetlabs.com/mac/puppet{{ puppet_version }}/{{ ansible_distribution_major_version }}.{{ ansible_distribution_version.split('.')[-2] }}/x86_64/puppet-agent-latest.dmg
        dest: ./tmp/puppet-agent-latest.dmg
      when: puppet_version == "5"

    - name: Darwin | Download puppet-agent package
      get_url:
        url: https://downloads.puppetlabs.com/mac/puppet{{ puppet_version }}/{{ ansible_distribution_major_version }}.{{ ansible_distribution_version.split('.')[-2] }}/x86_64/puppet-latest.dmg
        dest: ./tmp/puppet-agent-latest.dmg
      when: puppet_version == "6"

    # Don't know why it goes into error but it still works
    - name: Darwin | Mount dmg
      shell: hdiutil attach ./tmp/puppet-agent-latest.dmg -nobrowse -mountpoint ./tmp/puppet-agent-latest
      ignore_errors: yes

    - name: Darwin | Install puppet-agent
      shell: installer -pkg ./tmp/puppet-agent-latest/puppet-agent-*.pkg -target /

    - name: Darwin | Unmount and remove temporary directory
      shell: hdiutil detach ./tmp/puppet-agent-latest/ && rm -R ./tmp/

  when: puppet_package.stat.exists == False

- name: Darwin | Check if puppet service is running
  shell: launchctl list | grep puppet
  register: puppet_service
  changed_when: false
  ignore_errors: yes

- name: Darwin | Puppet-agent service
  shell: launchctl load -w /Library/LaunchDaemons/com.puppetlabs.puppet.plist
  when: puppet_service.rc != 0
