---

- name: Install puppet-agent from Puppetlabs reposiroty on Windows
  win_package:
    path: http://downloads.puppetlabs.com/windows/puppet5/puppet-agent-x64-latest.msi
    state: present

- name: Puppet-agent windows service
  win_service:
    name: puppet-agent
    start_mode: auto
    state: started
