---
dist: bionic
services:
  - docker

language: python
python:
  - "3.7"

env:
#-----------------------------------------------
#
# CentOS
#
#-----------------------------------------------
  - distribution: centos-8
    puppet_version: 5
  - distribution: centos-7
    puppet_version: 5
  - distribution: centos-6
    puppet_version: 5

#--------------------------------
#
# Fedora
#
#--------------------------------
  - distribution: fedora-30
    puppet_version: 5
  - distribution: fedora-29
    puppet_version: 5
  - distribution: fedora-28
    puppet_version: 5
  - distribution: fedora-27
    puppet_version: 5
  - distribution: fedora-26
    puppet_version: 5

#--------------------------------
#
# Ubuntu
#
#--------------------------------
  - distribution: ubuntu-18.04
    puppet_version: 5
  - distribution: ubuntu-16.04
    puppet_version: 5
  - distribution: ubuntu-14.04
    puppet_version: 5

#--------------------------------
#
# Debian
#
#--------------------------------
  - distribution: debian-10
    puppet_version: 5
  - distribution: debian-9
    puppet_version: 5
  - distribution: debian-8
    puppet_version: 5

#--------------------------------
#
# Oraclelinux
#
#--------------------------------
  - distribution: oraclelinux-8
    puppet_version: 5
  - distribution: oraclelinux-7
    puppet_version: 5
  - distribution: oraclelinux-6
    puppet_version: 5

#--------------------------------
#
# Amazonlinux
#
#--------------------------------
  - distribution: amazonlinux-2
    puppet_version: 5
  - distribution: amazonlinux-1
    puppet_version: 5

#--------------------------------
#
# Opensuse
#
#--------------------------------
  - distribution: opensuse-42.3
    puppet_version: 5
  - distribution: opensuse-13.2
    puppet_version: 5


before_install:
  - 'docker pull diodonfrost/${distribution}-ansible:latest'

install:
  - 'pip install -r requirements.txt'

script:
  - 'distribution=${distribution} packer_version=${packer_version} molecule test'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
