---
# tasks file for ansible-role-puppet

- name: Include OS specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install Puppetlabs repository
  include_tasks: "repository/install-repository.yml"
  when: puppetlabs_repository == true

- name: Install puppet-agent
  include_tasks: "agent/agent.yml"
  when: puppet_agent_install == true
