---
- name: Verify
  hosts: all
  tasks:
  - name: Linux | Puppet service should be functionnal
    command: systemctl status puppet
    register: puppet_service_result

  - name: Linux | Puppet command should be functionnal
    command: /opt/puppetlabs/bin/puppet --version
    ignore_errors: True
    failed_when: false
    register: puppet_os_binary_result

  - name: Linux | Puppet command should be functionnal
    command: puppet --version
    ignore_errors: True
    failed_when: false
    register: puppetlabs_binary_result

  - name: Linux | Verify commands outputs
    assert:
      that:
        - puppet_service_result.rc == 0
        - puppet_os_binary_result.rc == 0 or puppetlabs_binary_result.rc == 0
      success_msg: "All tests passed"
