# Install repository from Mariadb official repository

- name: "(Install: Centos/Debian/Fedora/Opensuse/RedHat/Ubuntu) Install Puppetlabs repository"
  block:

    - name: Puppetlabs Amazonlinux repos
      import_tasks: setup-CentOS.yml
      when: ansible_distribution  == "Amazon"

    - name: Puppetlabs CentOS repos
      import_tasks: setup-CentOS.yml
      when: ansible_distribution  == "CentOS"

    - name: Puppetlabs Debian repos
      import_tasks: setup-Debian.yml
      when: ansible_distribution  == "Debian"

    - name: Puppetlabs Fedora repos
      import_tasks: setup-Fedora.yml
      when: ansible_distribution  == "Fedora"

    - name: Puppetlabs OpenSuse repos
      import_tasks: setup-openSUSE Leap.yml
      when: ansible_distribution  == "openSUSE Leap"

    - name: Puppetlabs Oraclelinux repos
      import_tasks: setup-CentOS.yml
      when: ansible_distribution  == "OracleLinux"

    - name: Puppetlabs RedHat repos
      import_tasks: setup-CentOS.yml
      when: ansible_distribution  == "RedHat"

    - name: Puppetlabs Ubuntu repos
      import_tasks: setup-Ubuntu.yml
      when: ansible_distribution  == "Ubuntu"

    - name: Install puppet-agent from Puppetlabs reposiroty
      package:
        name: puppet-agent
        state: present
      when: ansible_system == "Linux"

    - name: Install puppet-agent from Puppetlabs reposiroty on Windows
      win_package:
        path: http://downloads.puppetlabs.com/windows/puppet5/puppet-agent-x64-latest.msi
        state: present
      when: ansible_system == "Windows"

    - name: Install puppet-server from Puppetlabs reposiroty
      package:
        name: puppet-server
        state: present
      when: puppet_server_install == true

  when: install_from == "puppetlabs_repository"

- name: "(Install: Centos/Debian/Fedora/Opensuse/RedHat/Ubuntu/bsd) Install Puppet with os repository"
  block:

    - name: Update apt cache
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_os_family == "Debian"

    - name: Puppet-agent install from os repository
      package:
        name: "{{ puppet_agent_package }}"
        state: present

    - name: Puppet-server install from os repository
      package:
        name: "{{ puppet_server_package }}"
        state: present
      when: puppet_server_install == true

  when: install_from == "os_repository"
